# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = true
[battery]
disabled = true

[character] # The name of the module we are configuring is "character"
error_symbol = "[❯](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
