#!/usr/bin/sh

sleep 0.1

title=$(playerctl -s metadata title)
artist=$(playerctl -s metadata artist)
if [ "$(playerctl -s status)" == "Paused" ]; then
        if [ $(echo $title | wc -c) -gt 15 ]; then
                i=12
                char=$(echo $title | cut -c $i)
                while [ "$char" == "\"" ] || [ "$char" == " " ] || [ "$char" == "-" ] || [ "$char" == "." ] || [ "$char" == "&" ] || [ "$char" == "(" ] || [ "$char" == "," ]; do
                        i=$(($i-1))
                        char=$(echo $title | cut -c $i)
                done
                echo {\"text\":\"$(echo ${title//\"/\\\"} | cut -c 1-$i)…  \", \"class\":\"spotify-paused\"}
        else
                echo {\"text\":\"${title//\"/\\\"}  \", \"class\":\"spotify-paused\"}
        fi
else
        if [ $(echo $title | wc -c) -gt 30 ]; then
                i=27
                char=$(echo $title | cut -c $i)
                while [ "$char" == "\"" ] || [ "$char" == " " ] || [ "$char" == "-" ] || [ "$char" == "." ] || [ "$char" == "&" ] || [ "$char" == "(" ] || [ "$char" == "," ]; do
                        i=$(($i-1))
                        char=$(echo $title | cut -c $i)
                done
                echo {\"text\":\"$(echo ${title//\"/\\\"} | cut -c 1-$i)… – $artist  \", \"class\":\"spotify-playing\"}
        else
                echo {\"text\":\"${title//\"/\\\"} – $artist  \", \"class\":\"spotify-playing\"}
        fi
fi
