#!/usr/bin/sh

title=$(playerctl metadata title)
artist=$(playerctl metadata artist)
if [ $(playerctl status) == "Paused" ]; then
        if [ $(echo $title | wc -c) -gt 15 ]; then
                i=12
                char=$(echo $title | cut -c $i)
                while [ "$char" == "\"" ] || [ "$char" == " " ] || [ "$char" == "-" ]; do
                        i=$(($i-1))
                        char=$(echo $title | cut -c $i)
                done
                echo $(echo $title | cut -c 1-$i)...
        else
                echo $(echo $title)
        fi
else
        if [ $(echo $title | wc -c) -gt 30 ]; then
                i=27
                char=$(echo $title | cut -c $i)
                while [ "$char" == "\"" ] || [ "$char" == " " ] || [ "$char" == "-" ]; do
                        i=$(($i-1))
                        char=$(echo $title | cut -c $i)
                done
                echo $(echo $title | cut -c 1-$i)... - $artist
        else
                echo $title - $artist
        fi
fi
