#!/usr/bin/sh

upgradable=$(yay -Qu | wc -l)
#upgradable=$(echo 3)

if [ "$upgradable" == "0" ]; then
        echo {\"class\": \"hidden\"}
else 
        if [ "$upgradable" == "1" ]; then
                echo {\"text\": \"1 update\", \"class\": \"update-count\"}
        else
                echo {\"text\": \"$upgradable updates!\", \"class\": \"update-count\"}
        fi
fi
