#!/bin/sh

pid=$(pidof waybar | awk '{print $1}')
while [[ $pid -gt 0 ]]; do
    kill -9 "$pid"
    pid=$(pidof waybar | awk '{print $1}')
done
    while pgrep -u $UID -x waybar > /dev/null; do sleep 1; done

swaymsg exec waybar

echo "Waybar launched"
